version: "3"
services:
  sensu-backend-1:
    container_name: sensu-backend-1
    image: sensu/sensu:latest
    hostname: sensu-backend-1
    restart: unless-stopped
    ports:
      - "2379:2379" # etcd client port
      - "2380:2380" # etcd peer port
      - "6060:6060" # Go debugging port
    labels:
      - "traefik.enable=false"
    networks:
      - sensu-load-balancer
      - sensu-backend
    volumes:
      - "./data1:/var/lib/sensu"
      - "./backend1.yml:/etc/sensu/backend.yml"
      - "../ssl:/etc/sensu/ssl"
    command: "sensu-backend start"
  sensu-backend-2:
    container_name: sensu-backend-2
    image: sensu/sensu:latest
    hostname: sensu-backend-2
    restart: unless-stopped
    ports:
      - "12379:2379"
      - "12380:2380"
    labels:
      - "traefik.enable=false"
    networks:
      - sensu-load-balancer
      - sensu-backend
    volumes:
      - "./data2:/var/lib/sensu"
      - "./backend2.yml:/etc/sensu/backend.yml"
      - "../ssl:/etc/sensu/ssl"
    command: "sensu-backend start"
  sensu-backend-3:
    container_name: sensu-backend-3
    image: sensu/sensu:latest
    hostname: sensu-backend-3
    restart: unless-stopped
    ports:
      - "22379:2379"
      - "22380:2380"
    labels:
      - "traefik.enable=false"
    networks:
      - sensu-load-balancer
      - sensu-backend
    volumes:
      - "./data3:/var/lib/sensu"
      - "./backend3.yml:/etc/sensu/backend.yml"
      - "../ssl:/etc/sensu/ssl"
    command: "sensu-backend start"
networks:
  sensu-load-balancer:
    external:
      name: sensu-load-balancer
  sensu-backend:
    external:
      name: sensu-backend
