version: "3"
services:
  sensu-agent-centos-1:
    container_name: sensu-agent-centos-1
    build:
      context: .
      dockerfile: Dockerfile_centos7
    image: toozej/sensu-agent-centos:7
    hostname: sensu-agent-centos-1
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    volumes:
      - "./data1:/var/lib/sensu"
      - "./agent1.yml:/etc/sensu/agent.yml"
    networks:
      - sensu-load-balancer
    command: "sensu-agent start"

  sensu-agent-centos-2:
    container_name: sensu-agent-centos-2
    build:
      context: .
      dockerfile: Dockerfile_centos7
    image: toozej/sensu-agent-centos:7
    hostname: sensu-agent-centos-2
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    volumes:
      - "./data2:/var/lib/sensu"
      - "./agent2.yml:/etc/sensu/agent.yml"
    networks:
      - sensu-load-balancer
    command: "sensu-agent start"
  
  sensu-agent-centos-3:
    container_name: sensu-agent-centos-3
    build:
      context: .
      dockerfile: Dockerfile_centos6
    image: toozej/sensu-agent-centos:6
    hostname: sensu-agent-centos-3
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    volumes:
      - "./data3:/var/lib/sensu"
      - "./agent3.yml:/etc/sensu/agent.yml"
    networks:
      - sensu-load-balancer
    command: "sensu-agent start"

networks:
  sensu-load-balancer:
    external:
      name: sensu-load-balancer
