FROM centos:6

RUN yum clean all && yum makecache && yum update -y
RUN curl -s https://packagecloud.io/install/repositories/sensu/stable/script.rpm.sh | bash
RUN yum install -y sensu-go-agent

EXPOSE 2379 2380 8080 8081 3000
CMD ["/usr/sbin/sensu-agent"]
