version: "3.0"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - sensu-load-balancer
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./data/:/var/lib/grafana/
      - ./provisioning/:/etc/grafana/provisioning/
      - ../ssl/:/etc/grafana/ssl/
    env_file:
      - grafana.env
    labels:
      - "traefik.enable=false"

networks:
  sensu-load-balancer:
    external:
      name: sensu-load-balancer
