---
type: Asset
api_version: core/v2
metadata:
  name: monitoring-plugins_centos_amd64
  labels: 
  annotations:
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/monitoring-plugins
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/monitoring-plugins
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.version: 2.2.0-2
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.name: monitoring-plugins
    io.sensu.bonsai.tags: ''
spec:
  url: https://assets.bonsai.sensu.io/8d83ae5503608d420810acd37a775f24e10dae17/monitoring-plugins-centos_2.2.0-2_linux_amd64.tar.gz
  sha512: c050df5a867675f12fce5d82b8828bad79b711e4d41bfa22f5f0dd0df7e33da5aa97acaef413b7129b8970d49e02db8f2b89e05de3be6f382cfb47da5bb3a002
  filters:
  - entity.system.os == 'linux'
  - entity.system.platform == 'centos'
  - entity.system.arch == 'amd64'

