---
type: Asset
api_version: core/v2
metadata:
  name: sensu-plugins-cpu-checks_centos_amd64
  labels: 
  annotations:
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-cpu-checks
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu-plugins/sensu-plugins-cpu-checks
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.version: 4.0.0
    io.sensu.bonsai.namespace: sensu-plugins
    io.sensu.bonsai.name: sensu-plugins-cpu-checks
    io.sensu.bonsai.tags: ruby-runtime-2.4.4
spec:
  url: https://assets.bonsai.sensu.io/68546e739d96fd695655b77b35b5aabfbabeb056/sensu-plugins-cpu-checks_4.0.0_centos_linux_amd64.tar.gz
  sha512: 518e7c17cf670393045bff4af318e1d35955bfde166e9ceec2b469109252f79043ed133241c4dc96501b6636a1ec5e008ea9ce055d1609865635d4f004d7187b
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
  - entity.system.platform == 'rhel'
