---
type: Asset
api_version: core/v2
metadata:
  name: sensu-plugins-cpu-checks_alpine_amd64
  labels: 
  annotations:
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-cpu-checks
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu-plugins/sensu-plugins-cpu-checks
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.version: 4.0.0
    io.sensu.bonsai.namespace: sensu-plugins
    io.sensu.bonsai.name: sensu-plugins-cpu-checks
    io.sensu.bonsai.tags: ruby-runtime-2.4.4
spec:
  url: https://assets.bonsai.sensu.io/68546e739d96fd695655b77b35b5aabfbabeb056/sensu-plugins-cpu-checks_4.0.0_alpine_linux_amd64.tar.gz
  sha512: b2da25ecd7642e6de41fde37d674fe19dcb6ee3d680e145e32289f7cfc352e6b5f9413ee9b701d61faeaa47b399aa30b25885dbc1ca432c4061c8823774c28f3
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
  - entity.system.platform == 'alpine'
