version: "3"
services:

  sensu-agent-debian-1:
    container_name: sensu-agent-debian-1
    build:
      context: .
      dockerfile: Dockerfile_debian9
    image: toozej/sensu-agent-debian:9
    hostname: sensu-agent-debian-1
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    volumes:
      - "./data1:/var/lib/sensu"
      - "./agent1.yml:/etc/sensu/agent.yml"
      - "../ssl:/etc/sensu/ssl"
    networks:
      - sensu-load-balancer
    command: "sensu-agent start"

  sensu-agent-debian-2:
    container_name: sensu-agent-debian-2
    build:
      context: .
      dockerfile: Dockerfile_debian10
    image: toozej/sensu-agent-debian:10
    hostname: sensu-agent-debian-2
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    volumes:
      - "./data2:/var/lib/sensu"
      - "./agent2.yml:/etc/sensu/agent.yml"
      - "../ssl:/etc/sensu/ssl"
    networks:
      - sensu-load-balancer
    command: "sensu-agent start"

networks:
  sensu-load-balancer:
    external:
      name: sensu-load-balancer
