FROM debian:8

RUN curl -s https://packagecloud.io/install/repositories/sensu/stable/script.deb.sh | bash
RUN apt-get update && apt-get install -y sensu-go-agent

EXPOSE 2379 2380 8080 8081 3000
CMD ["/usr/sbin/sensu-agent"]
