---
type: EventFilter
api_version: core/v2
metadata:
  annotations: null
  labels: null
  name: is_critical_incident
  namespace: default
spec:
  action: deny
  expressions:
    # deny (filter) event if status is warning (1) or OK (0)
    # to be used to avoid sending warnings and OKs to pager
    - event.check.status <= 1
  runtime_assets: []
