---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
      - github_actions
  schedule:
    - cron: "0 1 * * 1"

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Install pre-requisites
        run: sudo apt-get update -qq && sudo apt-get install -y libnss3-tools ca-certificates openssl

      - name: Install Sensu Go CLI tool
        run: curl -s https://packagecloud.io/install/repositories/sensu/stable/script.deb.sh | sudo bash && sudo apt-get install -y sensu-go-cli

      - name: Run compose project and check services are up and responding
        run: |
          chmod +x setuplab.sh && sudo ./setuplab.sh
          # add self-signed certificates to trusted certificates store using https://stackoverflow.com/questions/17597457/why-wont-curl-recognise-a-self-signed-ssl-certificate/21262787#21262787
          sudo cp ssl/ca/ca.pem /usr/local/share/ca-certificates/sensu_go_lab_ca.crt
          echo "sensu_go_lab_ca.crt" | sudo tee -a /etc/ca-certificates.conf
          sudo update-ca-certificates --fresh
          # curl compose projects to ensure they're actually running
          curl -s -L https://sensu.lab.test | grep "Client sent an API request to the web application port" ||  exit 1
          curl -s -L https://grafana.lab.test | grep Found ||  exit 1
          echo "if we got to this point the test has finished successfully, exiting." && exit 0
