version: "3"
services:
  sensu-load-balancer:
    container_name: sensu-load-balancer
    image: haproxy:latest
    hostname: sensu-load-balancer
    restart: unless-stopped
    ports:
      - "8000:70" # haproxy stats port
      - "443:3000" # sensu go webUI over https port 443
      - "8080:8080" # sensu go api port
      - "8081:8081" # sensu go agent transport port
    labels:
      - "traefik.enable=false"
    networks:
      - sensu-load-balancer
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
      - "../ssl:/etc/sensu/ssl"
networks:
  sensu-load-balancer:
    external:
      name: sensu-load-balancer
